### PR TITLE
Remove RDNN ID patch as it has been integrated into upstream

### PR DESCRIPTION
**Pull request by rugk**
Via https://gitlab.gnome.org/GNOME/simple-scan/-/merge_requests/269 the commit https://gitlab.gnome.org/GNOME/simple-scan/-/commit/c09a6def153e52494072a36233c7e7b3307b67bf fixed this upstream

So as far as I see, this patch is no longer relevant and may even lead to build problems.

### CODE REVIEW

**Comment by hfiguiere** [comment]
No it's not.

1. if it had be merged, the patch wouldn't apply and the build would have failed.
2. it is only in master
 
image

**Comment by rugk** [comment]
But is not master what it builds from? Strange thing here… And it has been merged into master so huh…

Ah maybe the pinned commit ID needs to be bumped too here?
https://github.com/flathub/org.gnome.SimpleScan/blob/ee5eb5b936de79d6c9d2f6f4ddea30fa1c29bbea/org.gnome.SimpleScan.json#L259

**Comment by rugk** [comment]
… whcih corresponds to the lastest release: https://gitlab.gnome.org/GNOME/simple-scan/-/commit/a42cc7bfba3766ddeaf8080ae7956951068a699d

So much words to say: you're still waiting for the next release, now I see, okay.

**Comment by hfiguiere** [comment]
it says `tag: 46.0`.

Not sure what is unclear. This is not for nightly builds.

**Pull request closed without merging**
